# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
